### ISSUE TITLE
Support for setting a managed identity

### ISSUE THREAD

**Issue by Jandev** [Azure-Samples/azure-event-grid-viewer#10]
### This issue is for a:
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
When deploying the EventGridViewer I would like to be able to set if it should use a Managed Identity or not.  
We now have a policy defined all Apps need a Managed Identity and I need to create an exemption for this service at the moment.

### Expected/desired behavior
Being able to set the option `SystemAssigned` or `None` when deploying the service.

### Additional details
I'm willing to pick this up myself if necessary.

**Comment by dbarkol** [comment]
Looks good. Thank you!
