### ISSUE TITLE
Should only be accessible over HTTPS

### ISSUE THREAD

**Issue by Jandev** [Azure-Samples/azure-event-grid-viewer#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a:
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
The deployed service should only allow traffic via HTTPS as it's the 'standard' for navigating websites nowadays.

### Any log messages given by the failure
>

### Expected/desired behavior
The option `"httpsOnly": true` is set in the ARM template for the deployed website.

### Mention any other details that might be useful
I'm willing to pick this up myself if you think this is a good idea.

**Comment by dbarkol** [comment]
thank you
