### ISSUE TITLE
It is no longer possible to deploy this

### ISSUE THREAD

**Issue by lucarv** [Azure-Samples/azure-event-grid-viewer#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Press the deploy to Azure button
### Any log messages given by the failure
>

### Expected/desired behavior
>
Template deploys

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 815e326d-d402-4a97-a470-a8e2286135e0"
    }
}
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hui-zhu** [comment]
I ran into the same issue in the past 3 days. My current workaround is to deploy App Service for .NET Core 3.1 with F1 sku from Azure portal first, and then download https://github.com/Azure-Samples/azure-event-grid-viewer/releases/download/230774/Azure_Event_Grid_Viewer.zip and open in Visual Studio. Eventually, deploying this Azure Event Grid app from VS 2019 to my websites.net instance.

**Comment by dbarkol** [comment]
looking into it now

**Comment by dbarkol** [comment]
Temporarily removed Identity from web site properties. It is failing when set to None.

**Comment by lucarv** [comment]
Deploying it with lets it go through. Not sure about the implications though, since the app does not work (might be unrelated.
When one tries to create an event subscription that terminates on the web app, it fails as below:

Deployment has failed with the following error: {"code":"Url validation","message":"Webhook validation handshake failed for https://banenor-api.azurewebsites.net/. Http POST request retuned 2XX response with response body \r\n\r\n\r\n    \r\n    \r\n    \r\n    \r\n    \r\n\r\n\r\n    
\r\n        \r\n
\r\n    
\r\n

**Comment by dbarkol** [comment]
Can you provide some repro steps, please? Just tested a new deployment with both the event grid and cloud event schemas and it seemed to work as expected.

**Comment by lucarv** [comment]
Just follow the tutorial (only that set the identity as oppose to using none). 
- Deploy the app
- Create an event grid subscription that points to the newly created app
- See the handshake failing with the error above

**Comment by dbarkol** [comment]
Looks like many docs still point to the older master branch, which still has the Identity option. I'll remove that option now. 

Would you mind referencing a specific tutorial? I ran through most of them (with CLI and Portal).

**Comment by lucarv** [comment]
The one I was referring too now works.
https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart-portal#subscribe-to-custom-topic

**Comment by hui-zhu** [comment]
I used https://docs.microsoft.com/en-us/samples/azure-samples/azure-event-grid-viewer/azure-event-grid-viewer and https://docs.microsoft.com/en-us/azure/event-grid/custom-event-quickstart . both of them are working now. 
additional reference is from https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/telephony-sms/handle-sms-events

**Comment by dbarkol** [comment]
Thank you for catching this and for all the feedback, everyone.

**Comment by SeaDude** [comment]
Ensure the Github branch name is set to `main` not the older default naming convention of `master`. 

See #23 .
