### ISSUE TITLE
add app service hostname as output parameter

### ISSUE THREAD

**Issue by grayjeremy** [Azure-Samples/azure-event-grid-viewer#3]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
### Expected/desired behavior
> The ARM template should output the name of the host that it creates
### Mention any other details that might be useful
This helps chain this ARM deployment to other downstream requests.  I created a terraform module that uses this called [eventgrid-blob](https://github.com/grayjeremy/terraform-azurerm-eventgrid-blob) that needs to have this parameter output.  This also works for the method of chaining ARM templates into seperate deployments in lieu of creating a single large script. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grayjeremy** [comment]
fixed in https://github.com/Azure-Samples/azure-event-grid-viewer/pull/2

**Comment by dbarkol** [comment]
Thank you!
