### ISSUE TITLE
No way to deploy the this app

### ISSUE THREAD

**Issue by RaniRaven** [Azure-Samples/azure-event-grid-viewer#4]
I thought at first that this is something simple, but working directly with the given example for the names of the plan and the site, create a conflict while trying to deploy the site.
As the error message is not very in formative, saying something like "the name already exists" and I cannot figure out why, because it seems like the script is trying to create the exact same thing twice, and create something wrong within the deployment.
Couldn't solve this issue, like something is wrong in the scripts, and I wonder, is it due to changes in azure ?

**Comment by dbarkol** [comment]
You need to come up with a unique name for the site. If you tried to use the same name as the one used in the screen shot, it's likely taken.
