### ISSUE TITLE
Updates to validation in Azure have broken ability to add a webhook to this project

### ISSUE THREAD

**Issue by sapeavy** [Azure-Samples/azure-event-grid-viewer#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Try to validate using the new cloud event schema in Azure.
### Any log messages given by the failure
>

### Expected/desired behavior
>
I expect that it should validate and add the webhook endpoint.
### Versions
>

### Mention any other details that might be useful
It appears that "aeg-event-type" is no longer used for validation. It should instead check the method for "OPTIONS" and use the "WebHook-Request-Origin" as the return value.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sapeavy** [comment]
This is related to changes for Cloud Events schema 1.0. The cloud event model spec has also updated.

**Comment by dbarkol** [comment]
This was updated in November 2019 to support both the eventgrid schema as well as the cloudevents 1.0 schema. See the UpdatesController for details on how both are supported (OPTIONS for cloudevents and POST for validation of the original event grid handshake). For further details about the implementation, please see: https://madeofstrings.com/2020/01/21/webhooks-with-azure-event-grid-and-cloudevents-v1-0/
